name = "NestedTuples"
uuid = "a734d2a7-8d68-409b-9419-626914d4061d"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.3.8"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
Accessors = "0.1"
ArraysOfArrays = "0.5"
BangBang = "0.3"
GeneralizedGenerated = "0.3"
NamedTupleTools = "0.13, 0.14"
Static = "0.6"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
